config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users
  resources :beds do
    resources :bookings, only: [:create]

  end
  resources :bookings, only: [:index, :show, :destroy, :update] do
      resources :reviews, only: [:create, :index, :show]
    end

  namespace :my do
    resources :beds, only: [:index]
    resources :bookings, only: [:index, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  BLANKET = ["Wool blanket", "duvet", "sleeping bag", "none"]

  belongs_to :user
  validates :address, presence: true
  validates :title, presence: true
  validates :photo, presence: true
  validates :price, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :blanket_type, inclusion: { in: BLANKET,
      message: "%{value} is not a valid blanket type" }, presence: true

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_attachment :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bed
  has_one :review
  validates :checkin_on, presence: true
  validates :checkout_on, presence: true
  validates :status, inclusion: { in: ["Pending guest request", "Pending host validation", "Confirmed", "Canceled"], allow_nil: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  GENDER = %w(Woman Man Both)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :gender, presence: true, inclusion: { in: GENDER,
      message: "%{value} is not a valid gender" }
  validates :photo, presence: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  has_many :beds, dependent: :destroy
  has_many :bookings
  has_many :reviews, through: :bookings
  # has_many :bookings, through: :beds
  has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :gender_preferences, :description, :photo ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :gender, :gender_preferences, :description, :photo ])
  end



end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
skip_before_action :authenticate_user!, only: [:new, :index]

  def index
    @beds = Bed.all

    @beds = Bed.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@beds) do |bed, marker|
      marker.lat bed.latitude
      marker.lng bed.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
    @bed = Bed.new
    # @user = current_user
  end

  def create
    @bed = Bed.create(bed_params)
    @bed.user = current_user
    if @bed.save
      redirect_to bed_path(@bed)
    else
      render :new
    end
  end

  def show
    set_bed

    @booking = Booking.new
    @checkin = params['checkin_on']
    @checkout = params['checkout_on']
    if ((!@checkin.blank?) && (!@checkout.blank?))
      from = @checkin.split("/")
      to = @checkout.split("/")
      start = Date.new(from[2].to_f, from[1].to_f - 1, from[0].to_f)
      finish = Date.new(to[2].to_f, to[1].to_f - 1, to[0].to_f)
      @nb_days = (finish - start).to_f
      @total_price = (@nb_days * @bed.price.to_f).round
    end
    @bed = Bed.find(params[:id])
    @bookings = @bed.bookings
    @alert_message = "You are viewing the bed of #{@bed.user.first_name}"
  end

  def edit
    set_bed
  end


  def update
    set_bed
    @bed.update(bed_params)
    redirect_to bed_path(@bed)
  end

  def destroy
    set_bed
    @bed.destroy
    redirect_to root_path
  end


  private

  def bed_params
    params.require(:bed).permit(:address, :title, :photo, :price, :description, :country, :city, :zipcode, :photo, :blanket_type, :pillow, :breakfast)
  end

  def set_bed
    @bed = Bed.find(params[:id])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def create
    @bed = Bed.find(params[:bed_id])
    @booking = Booking.new(booking_params)
    @booking.bed = @bed
    @booking.user = current_user
    @booking.status = "Pending host validation"
    if @booking.checkout_on && @booking.checkin_on
      @booking.value = (@booking.checkout_on - @booking.checkin_on).to_f * @booking.bed.price.to_f
    else
      @booking.value = 0
    end
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to bed_path(@bed)
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
    @review = Review.new
  end

  def show
    set_booking
    @bed = @booking.bed
  end

  def update
    set_booking
    @booking.status = "Pending host validation"
    @booking.save!
    redirect_to booking_path(@booking)
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to root_path
  end

  private

  def booking_params
    params.require(:booking).permit(:checkin_on, :checkout_on, :value, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/my/beds_controller.rb
class My::BedsController < ApplicationController
  def index
    @beds = current_user.beds
  end
end

app/controllers/my/bookings_controller.rb
class My::BookingsController < ApplicationController
  def index
    @beds = current_user.beds
  end

  def update
    set_booking
    @booking.update(set_params)
    redirect_to my_bookings_path
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_params
    params.require(:booking).permit(:status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
    @bed = Bed.new
    @beds = Bed.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_booking, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.save
    redirect_to bookings_path
  end

  private
  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/beds/edit.html.erb
<h2 class="text-center">Modify your bed <strong id="red-word">description</strong> so that it is even <strong id="red-word">sexier</strong> !</h2>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-login text-left">
      <h2 class="text-center">My bed infos</h2>
        <br>
        <%= simple_form_for @bed do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :city %>
        <%= f.input :country %>
        <%= f.input :description %>
        <%= f.input :price %>
        <br>
        <%= f.input :photo, as: :attachinary%>
        <br>
        <h3><strong>Equipments</strong></h3>
        <%= f.input :pillow, as: :boolean, label: "Will your guest have his own pillow?" %>
        <%= f.input :breakfast, as: :boolean, label: "Do you serve breakfast in bed?" %>
        <br>
        <%=  f.input :blanket_type, collection: Bed::BLANKET, label: "What kind of blanket are you providing?" %>
        <hr>
        <%= f.button :submit, "Modify your bed", class: "btn btn-danger"%>
        <%= link_to "Delete #{@bed.title}", bed_path(@bed),
        method: :delete,
        data: { confirm: "Are you sure?" }, class: "btn btn-success"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/beds/index.html.erb
<h1 class="text-center title-index-padding">Find your <strong id="title-index">Sharer</strong> and a <strong id="title-index">comfy</strong> bed</h1>


<div class="container-fluid">

  <div class="col-sm-7">
    <div class="row">
      <% @beds.each do |bed| %>
        <div class="col-xs-12 col-sm-6">
          <%= link_to bed_path(bed,checkin_on: params[:checkin], checkout_on: params[:checkout]) do %>
            <div class="cardContainer">
              <div class="card-image"
                  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bed.photo.path, width: 400,height: 300, crop: :thumb %>')">
                <div class="card-first-name"><%= bed.user.first_name %></div>
                <%= cl_image_tag bed.user.photo.path, width: 50, height: 50, crop: :thumb, gravity: :face, class: "card-user avatar" %>
              </div> <!-- fin card-image -->
              <div class="card">
                <div class="card-description">
                  <p><strong id="city"><%= bed.city %></strong></p>
                  <p><%= bed.title %></p>
                </div>
                <div class="card-price">
                  <h2> <%= bed.price %> €</h2>
                </div> <!-- fin card-price -->
              </div> <!-- fin card -->
            </div> <!-- fin cardContainer -->
          <% end %>
        </div> <!-- fin de col -->
      <% end %>
    </div>  <!-- fin du row -->
  </div> <!-- fin du col-sm-8 -->

  <div class="col-sm-5">
    <div class="beds-map-wrapper">
      <div id="beds-map" style="width: 100%; height: 400px;"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({
        provider: {
          scrollwheel: false,
          zoomControl: false
        },
        internal: { id: 'beds-map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });

  <% end %>
<% end %>

app/views/beds/new.html.erb
<h2 class="text-center">Share your <strong id="red-word">bed</strong> with the community. Be <strong id="red-word">fun</strong> and <strong id="red-word">sexy</strong> ! </h2>

<div id="wrapper">
  <div class="row">
    <div class="text-left form-login">
      <h2 class="text-center"><strong>Add my Bed </strong></h2>
      <br>
      <%= simple_form_for @bed do |f| %>
      <%= f.error_notification %>
      <%= f.input :title, placeholder: "Warm bed with silk sheets", :label_html => { :class => "label-css"} %>
      <%= f.input :address, label: "My lovely nest is located at this address", placeholder: "36 avenue du calin" %>
      <%= f.input :city, placeholder: "Bisouville" %>
      <%= f.input :country, priority: ["France"] %>
      <%= f.input :description, label: "A sexy description for a warm bed", placeholder: "I live in a cosy house in the countryside. I love hugs and spending the night with strangers. My bed has high tech silk sheets and a warm pink blanket. Don't hesitate: Book a night (or more)" %>
      <%= f.input :price, label: "Price per night in €", placeholder: "48" %>
      <br>
      <%= f.input :photo, as: :attachinary, label: "Choose a nice picture for your bed" %>
      <br>
      <hr>
      <h4><strong>EQUIPEMENTS</strong> </h4>
      <br>
      <%= f.input :pillow, as: :boolean, label: "Providing a pillow?" %>
      <%= f.input :breakfast, as: :boolean, label: "Serving breakfast in bed?" %>
      <%= f.input :blanket_type, collection: Bed::BLANKET, label: "What kind of blanket are you providing?" %>
      <br>
      <hr>
      <%= f.button :submit, "Share my bed", class: "btn btn-danger btn-lg"%>

      <% end %>
    </div>
  </div>

</div>
</div>


<%= content_for(:after_js) do %>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyC8nUa2rua2jKRMY-bKdEW9GxRRh55wtIg"></script>
<% end %>

</div>

app/views/beds/show.html.erb
<h1 class="text-center"><%= @bed.title %></h1>

<div class="container">

  <div class="row">
    <div class ="photo-row">
      <div class="col-xs-12 col-sm-6">
        <div class="card showmaincard"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @bed.photo.path, height: 300, width: 400, crop: :fill %>')">
        </div>
      </div>

      <div class="col-xs-12 col-sm-6">
        <div class="wagoncard showmaincard">
            <div class="wagoncard-category"> <strong> <%= @bed.user.first_name %> </strong> </div>
            <div class="wagoncard-detail">
              <p>Sex: <strong> <%= @bed.user.gender %> </strong> </p>
              <p>Interested in: <strong> <%= @bed.user.gender_preferences %> </strong> </p>
              <i class="fa fa-book" aria-hidden="true"></i>
              <i>" <%= @bed.user.description %> "</i>
            </div>
          <%= cl_image_tag @bed.user.photo.path, width: 50, height: 50, class: "wagoncard-user avatar avatar-semi" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">

      <p> <i class="fa fa-map-marker" aria-hidden="true"></i> <%= @bed.address %> <%= @bed.city %> <%= @bed.country %></p>
      <p> <i class="fa fa-eur" aria-hidden="true"></i> <%= @bed.price %> per night ... but so much love</p>
      <p> <strong>Description:</strong> </p>
      <p><%= @bed.description %></p>
      <div class = "equipment-div">
        <p><strong>Equipments</strong></p>
        <i class="fa fa-bed pad" aria-hidden="true"> <%= @bed.blanket_type %>  </i>
        <%= image_tag "pillow.jpg", class: "equipment" %>
          <% if @bed.pillow %>
            <i class="fa fa-check pad" aria-hidden="true"></i>
          <% else %>
            <i class="fa fa-times pad" aria-hidden="true"></i>
          <% end %>

        <i class="fa fa-coffee fa-lg " aria-hidden="true" ></i>
        <% if @bed.breakfast %>
          <i class="fa fa-check pad" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-times pad" aria-hidden="true"></i>
        <% end %>
      </div>

      <div>
        <p><strong>Reviews</strong></p>
        <% @bookings.each do |booking|%>
        <ul class="list-inline">
         <% if booking.review %>
            <li class="list-unstyled">
            <div class="review-chat">
              <%= cl_image_tag booking.user.photo.path, width: 50, height: 50, crop: :thumb, gravity: :face, class: "avatar"  %>
              <div class="review-comment">
                <% booking.review.rating.times do %>
                <i class="fa fa-star" aria-hidden="true" ></i>
                <% end %>
                <% (5- booking.review.rating).times do %>
                  <i class="fa fa-star-o" aria-hidden="true"></i>
                <% end %>
                <p> <%= booking.review.content %> </p>
              </div>
            </div>
            </li>
          <% end %>
         </ul>
       <% end %>
     </div>

    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="text-center">
        <%= simple_form_for [@bed, @booking] do |f| %>

          <div class="booking-card">
            <div >
            <p>From </p>
            <%= f.text_field :checkin_on, class: "datepicker checkin_on", value: @checkin, placeholder: "dd/mm/yyyy" %>
            </div>
            <div>
            <p> To </p>
            <%= f.text_field :checkout_on, class: "datepicker checkout_on", value: @checkout, placeholder: "dd/mm/yyyy" %>
            </div>
            <p> <strong>Total price: <span id="total_price"><%= @total_price %> €</span></strong></p>
            <%= f.submit "Book", class: "btn btn-danger"%>
          </div>

        <% end%>

      </div>
    </div>
  </div>
</div>

<div id="static-map"></div>


<% content_for(:after_js) do %>


  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
      handler.buildMap({
        provider: {
          scrollwheel: false,
          zoomControl: false
        },
        internal: { id: 'static-map' }
      }, function(){
        markers = handler.addMarkers([
          {
            "lat": <%= @bed.latitude  %>,
            "lng": <%= @bed.longitude %>,

          },
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(15);
      });
      $(".checkin_on, .checkout_on").on("change", function(e) {
        var from = $(".checkin_on").val().split("/");
        var to = $(".checkout_on").val().split("/");
        var start = new Date(from[2], from[1] - 1, from[0]);
        var end = new Date(to[2], to[1] - 1, to[0]);
        var nb_days = Math.round((end - start)/(1000*60*60*24));
        var total_price = nb_days * <%= @bed.price %> || 0 ;
        $("#total_price").html(total_price + " €");
      });
    });
  </script>

<% end %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <% if @booking.status == "Pending host validation"%>
      <h3>  <strong><i class="fa fa-star" aria-hidden="true"></i> We are waiting for <%= @booking.bed.user.first_name %> to confirm your request </strong> <i class="fa fa-star" aria-hidden="true"></i></h3>
      <h3> So... stay tuned! </h3>
      <% end %>
      <hr>

        <div class="row">
          <div class="col-md-6">
            <%= cl_image_tag @booking.bed.user.photo.path, width: 150, height: 150, crop: :thumb, class: "avatar-xlarge" %>
          </div>
          <div class="col-md-6">
              <div class="text-left">
              <h4> Reminder of your <strong id="red-word">booking details</strong></h4>
              <br>
                <table>
                 <tbody>
                    <tr>
                      <td> <h4><i class="fa fa-heart" aria-hidden="true"></i> </h4></td>
                      <td><h4> &nbsp; Your host is <strong> <%= @booking.bed.user.first_name %> </strong></h4></td>
                    </tr>
                    <tr>
                      <td><h4> <i class="fa fa-bed" aria-hidden="true"></i></h4></td>
                      <td><h4> &nbsp; You asked to join a warm bed from : <br>  &nbsp;   <%= @booking.checkin_on %> to <%= @booking.checkout_on %> </h4></td>
                    </tr>
                    <tr>
                      <td><h4> <i class="fa fa-thumbs-up" aria-hidden="true"></i></h4></td>
                      <td><h4> &nbsp; The total price for your booking is <%= @booking.value %> €</h4></td>
                    </tr>
                  </tbody>
                </table>
              </div>
          </div>
        </div>


      <% if @booking.status == "Pending guest request"%>
      <%= simple_form_for(@booking) do |f| %>
      <%= f.submit "Confirm my booking", class: "btn btn-danger btn-lg" %>
      <% end %>
      <% end %>
      <hr>
    <%= link_to "See my next stays", bookings_path, class:"btn btn-default btn-lg " %>
    </div>
  </div>
</div>
</div>

app/views/my/beds/index.html.erb
<div class="text-center">
  <h2>Here are all the <strong id="red-word">beds</strong> you are sharing!</h2>
</div>


<div class="wrapper-dashboard padded">
  <ul class="list-unstyled">
    <% @beds.each do |bed| %>
    <li class="padded dashboard">
      <%= cl_image_tag(bed.photo.path, width: 400, height: 300, crop: :fill, class: "pdt-image hidden-xs" ) %>

      <div class='product-body'>

        <h2><strong><%= bed.title %></strong></h2>
        <h4>Located in <strong><%= bed.city %></strong></h4>
        <h4>Description: <%=bed.description%></h4>
        <h4>Price: <strong><%= bed.price %>€/night </strong></h4>
      </div>

      <ul class="list-inline hidden-sm hidden-xs">
        <%= link_to "Edit this bed", edit_bed_path(bed), class:"btn btn-default-black"%>
      </ul>

    </li>
      <hr>
      <% end %>
  </ul>
</div>

app/views/my/bookings/index.html.erb
<div class="text-center">
  <h2> Wahou ! You are so attractive </h2>
  <h3>See who wants to sleep with you !</h3>
</div>

<div class="wrapper-dashboard">

  <ul class="list-unstyled">
    <% @beds.each do |bed| %>

    <% bed.bookings.each do |booking| %>
    <li class="padded dashboard">


      <% if booking.status == "Pending host validation" %>
      <%= cl_image_tag(booking.user.photo.path, width: 400, height: 300, crop: :fill, class: "product-image hidden-xs" ) %>

      <div class='product-body'>

        <h3> <%= booking.user.first_name %> wants to stay with you ! </h3>
        <p> Dates : <%= booking.checkin_on %> and <%= booking.checkout_on %> </p>
        <p> On top of having a great night, you will make <%= booking.value %> € </p>

       <!-- end of product-body -->

      <ul class="list-inline product-controls hidden-sm hidden-xs">
        <li><%= link_to "Accept ", my_booking_path(booking, booking: {status: "Confirmed"}), method: :patch, class: "btn btn-success"%></li>
        <li><%= link_to "Decline", my_booking_path(booking, booking: {status: "Canceled"}), method: :patch, class: "btn btn-danger"%></li>
      </ul>

      <% elsif booking.status == "Confirmed" %>
      <%= cl_image_tag(booking.user.photo.path, width: 400, height: 300, crop: :fill, class: "product-image hidden-xs" ) %>

      <div class='product-body'>
        <h3 class="congrat-text"> Congrats ! <%= booking.user.first_name %> is staying with you </h3>
        <p> Dates : <%= booking.checkin_on %> to <%= booking.checkout_on %> </p>
        <p> You will make : <%= booking.value %> € </p> <br>
        <p> Prepare your bed !</p>
      </div>

      <ul class="list-inline product-controls hidden-sm hidden-xs">
        <li><p> Status </p> <p> <i class="fa fa-check-square-o icon-validate" aria-hidden="true"></i></p></li>
      </ul>

      <% elsif booking.status == "Canceled" %>
      <%= cl_image_tag(booking.user.photo.path, width: 400, height: 300, crop: :fill, class: "product-image hidden-xs" ) %>

      <div class='product-body'>
        <h3 class="congrat-text"> We are so sorry... You won't stay with <%= booking.user.first_name %> </h3>
        <p> Dates : <%= booking.checkin_on %> to <%= booking.checkout_on %> </p>
      </div>

      <ul class="list-inline product-controls hidden-sm hidden-xs">
        <li><p> Status </p> <p> <i class="fa fa-times icon-validate" aria-hidden="true"></i></p></li>
      </ul>

      <% end %>
    </li>
    <hr>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [ booking, review ], url: booking_reviews_path(booking), method: :post do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.input :rating%>
  <%= form.button :submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "/logo-pink.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <div>
        <div class="dropdown">
          <%= link_to "Host", beds_path, class: "navbar-wagon-item navbar-wagon-link dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class="text-center">
              <%= link_to "Add my bed", new_bed_path %>
            </li>
            <li class="text-center">
              <%= link_to "See my beds", my_beds_path %>
            </li>
            <li class="text-center">
              <%= link_to "Who wants to sleep with me  ", my_bookings_path%>
              <div class="badge-container">
              <div class="badge badge-red">N</div>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <%= link_to "My stays", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo.path, crop: :fill, class: "avatar-navbar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class="text-center">
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li class="text-center">
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li class="text-center">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>



    <% else %>

      <div class="navbar-wagon-item">
      <%= link_to t(".new", default: "Add my bed"), new_bed_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>